### ISSUE TITLE
Two issues: Null pointer exception and MNIST downloader solution

### ISSUE THREAD

**Issue by ldmtwo** [deeplearning4j/dl4j-spark-cdh5-examples#18]
Two problems: The downloader (fixed) and this exception. I really don't have much info on the exception. It ran for a while and then crashed.

To get MNIST data to work, I had to track down the code the actually downloaded the examples. This is absolutely in the wrong place. https://github.com/deeplearning4j/deeplearning4j/blob/b1ffaddb67b6cf89ee97d40db931dd95f6cab742/deeplearning4j-core/src/main/java/org/deeplearning4j/base/MnistFetcher.java

In Spark and especially CDH Spark, it is very difficult to change or use user.home. HDFS or a user defined path is the way to go.

For anyone needing this answer/hack, you simply need to take the 4 files below. Download and rename the files like this.

`wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz -O ~/MNIST/images-idx3-ubyte.gz`
et cetera

```
	protected File BASE_DIR = new File(System.getProperty("user.home"));
	protected static final String LOCAL_DIR_NAME = "MNIST";
	protected File FILE_DIR = new File(BASE_DIR, LOCAL_DIR_NAME);

	private File fileDir;
	private static final String trainingFilesURL = "http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz";
	private static final String trainingFilesFilename = "images-idx3-ubyte.gz";
	public static final String trainingFilesFilename_unzipped = "images-idx3-ubyte";
	private static final String trainingFileLabelsURL = "http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz";
	private static final String trainingFileLabelsFilename = "labels-idx1-ubyte.gz";
	public static final String trainingFileLabelsFilename_unzipped = "labels-idx1-ubyte";

	//Test data:
	private static final String testFilesURL = "http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz";
	private static final String testFilesFilename = "t10k-images-idx3-ubyte.gz";
	public static final String testFilesFilename_unzipped = "t10k-images-idx3-ubyte";
	private static final String testFileLabelsURL = "http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz";
	private static final String testFileLabelsFilename = "t10k-labels-idx1-ubyte.gz";
	public static final String testFileLabelsFilename_unzipped = "t10k-labels-idx1-ubyte";


	public  File downloadAndUntar() throws IOException {
		if (fileDir != null) {
			return fileDir;
		}

		File baseDir = FILE_DIR;
		if (!(baseDir.isDirectory() || baseDir.mkdir())) {
			throw new IOException("Could not mkdir " + baseDir);
		}

		log.info("Downloading mnist...");
		// getFromOrigin training records
		File tarFile = new File(baseDir, trainingFilesFilename);
		File tarFileLabels = new File(baseDir, testFilesFilename);
```

```
java.lang.NullPointerException
        at org.nd4j.linalg.api.shape.Shape.rank(Shape.java:1406)
        at org.nd4j.linalg.api.ndarray.BaseNDArray.rank(BaseNDArray.java:3922)
        at org.nd4j.linalg.dataset.DataSet.merge(DataSet.java:114)
        at org.deeplearning4j.spark.impl.multilayer.IterativeReduceFlatMap.call(IterativeReduceFlatMap.java:85)
        at org.deeplearning4j.spark.impl.multilayer.IterativeReduceFlatMap.call(IterativeReduceFlatMap.java:49)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$5$1.apply(JavaRDDLike.scala:167)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$5$1.apply(JavaRDDLike.scala:167)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$17.apply(RDD.scala:706)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:297)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:262)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by raver119** [comment]
Please attach actual pom.xml you're using.

**Comment by andycui97** [comment]
I have the same issue, but I am building with sbt, so here's my build.sbt

```
name := "deeplearning4j-examples-scala"

version := "1.0"

scalaVersion := "2.11.7"

lazy val root = project.in(file("."))

classpathTypes += "maven-plugin"

libraryDependencies ++= Seq(
  "org.deeplearning4j" % "deeplearning4j-core" % "0.4-rc3.10",
  "org.nd4j" % "nd4j-native" % "0.4-rc3.10" classifier "" classifier "linux-x86_64",
  "org.nd4j" % "nd4j-api" % "0.4-rc3.10",
  "org.scala-lang" % "scala-library" % "2.11.7",
  "org.apache.spark" % "spark-mllib_2.11" % "1.6.0",
  "org.deeplearning4j" % "dl4j-spark_2.11" % "0.4-rc3.10",
  "org.deeplearning4j" % "deeplearning4j-ui" % "0.4-rc3.10",
  "org.apache.spark" % "spark-core_2.11" % "1.6.0"
).map(_.exclude("org.slf4j", "slf4j-log4j12")).map(_.exclude("org.nd4j", "canova-nd4j-image"))

dependencyOverrides ++= Set(
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.4.4"
)


resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

resolvers += "Sonatype release Repository" at "http://oss.sonatype.org/service/local/staging/deploy/maven2/"

resolvers += "Local Maven Repository" at "file:///"+Path.userHome.absolutePath+"/.m2/repository/"

assemblyMergeStrategy in assembly := {
  case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.last
}

```
For reference I am using spark-1.6 and my project is in scala 2.11.7

**Comment by AlexDBlack** [comment]
Kyro serialization required the use of a custom registrator. Not having that will case NPEs.

See javadoc here: https://github.com/deeplearning4j/nd4j/blob/4b9321cf4eef792016f613b522333b8bda65b48c/nd4j-serde/nd4j-kryo/src/main/java/org/nd4j/Nd4jRegistrator.java#L8

Next release of DL4J will have a warning for this situation: see also message there
https://github.com/deeplearning4j/deeplearning4j/blob/c5d0f42d0d571c12b465b4774f3f62aa8fa8cfc4/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/util/SparkUtils.java#L50

**Comment by jpatanooga** [comment]
ultimately we need to create a new spark examples rep with spark { local,
cdh, hdp } example jobs in it and deprecate this one
