### ISSUE TITLE
Couldn't run spark example org.deeplearning4j.examples.cnn.MnistExample

### ISSUE THREAD

**Issue by hhhhzzz** [deeplearning4j/dl4j-spark-cdh5-examples#8]
First try gave me:
]Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 42 in stage 4.0 failed 4 times, most recent failure: Lost task 42.3 in stage 4.0 (TID 543, simfarm755.dft.twosigma.com): java.lang.NullPointerException
        at org.deeplearning4j.nn.updater.MultiLayerUpdater.access$000(MultiLayerUpdater.java:20)
        at org.deeplearning4j.nn.updater.MultiLayerUpdater$MultiLayerUpdaterAggregator.aggregate(MultiLayerUpdater.java:78)
        at org.deeplearning4j.spark.impl.common.updater.UpdaterElementCombiner.call(UpdaterElementCombiner.java:11)
        at org.deeplearning4j.spark.impl.common.updater.UpdaterElementCombiner.call(UpdaterElementCombiner.java:8)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction2$1.apply(JavaPairRDD.scala:1012)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
        at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$21.apply(RDD.scala:1098)
        at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$21.apply(RDD.scala:1098)
        at org.apache.spark.SparkContext$$anonfun$36.apply(SparkContext.scala:1954)
        at org.apache.spark.SparkContext$$anonfun$36.apply(SparkContext.scala:1954)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1835)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1955)
        at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1100)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
        at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1093)
        at org.apache.spark.api.java.JavaRDDLike$class.aggregate(JavaRDDLike.scala:411)
        at org.apache.spark.api.java.AbstractJavaRDDLike.aggregate(JavaRDDLike.scala:46)
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.runIteration(SparkDl4jMultiLayer.java:372)
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:281)
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:255)
        at org.deeplearning4j.examples.cnn.MnistExample.main(MnistExample.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:735)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:182)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:207)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:122)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

If I keep trying the example, sometimes it gave an error earlier than that point:
Exception in thread "main" java.lang.IllegalStateException: No updater to combine
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.runIteration(SparkDl4jMultiLayer.java:382)
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:281)
        at org.deeplearning4j.spark.impl.multilayer.SparkDl4jMultiLayer.fitDataSet(SparkDl4jMultiLayer.java:255)
        at org.deeplearning4j.examples.cnn.MnistExample.main(MnistExample.java:132)

Notice the code in main already have the following lines:
        MultiLayerConfiguration conf = builder.build();
        MultiLayerNetwork net = new MultiLayerNetwork(conf);
        net.init();
        net.setUpdater(null);   //Workaround for minor bug in 0.4-rc3.8

**Comment by maybecan** [comment]
Have you solved this problem? I've encounted the question with "OutOfMemory",how about you?

**Comment by AlexDBlack** [comment]
Apologies, I didn't see this issue until now.
This was a problem with 0.4-rc3.8 that has already been fixed in DL4J master here: https://github.com/deeplearning4j/deeplearning4j/pull/1028
